### PR TITLE
Merging with master and adding some java-doc comments

### PR DESCRIPTION
**Pull request by Megala21**

### CODE REVIEW

**Comment by rasika** [comment]
@Megala21 this looks bit bulky with the formatting changes. Shall we create a new PR with only java-doc comments additions?

**Review by rasika — DISMISSED** [review]
.

**Review by rasika — CHANGES_REQUESTED** [review]
@Megala21 this looks bit bulky with the formatting changes. Shall we create a new PR with only java-doc comments additions?

**Comment by Megala21** [comment]
@rasika - This PR is for application-mgt branch. Not master branch. Since the application-mgt branch is behind the master branch, it has resulted in this bulk PR.

**Pull request merged**
